// aplus_kbone/src/pages/click/click.vue
<template>
    <div class="event-click" v-on:click="onAplusClk">
        <div class="click-detail">
            <img src="https://gd1.alicdn.com/imgextra/i4/2207297515629/O1CN01W5rDzt1rS89qNHD1f_!!2207297515629.jpg_400x400.jpg" alt=""/>
            <view>
                <p>{{'商品名称'}}: {{detail.product}}</p>
				<p>{{'商品颜色'}}: {{detail.productColor}}</p>
				<p>{{'商品ID'}}: {{detail.productId}}</p>
            </view>
        </div>
        <div class="click-purchase">
            <button id="test_111" data-product="ceshi" class="auto-click" type="default" :data-product="detail.product" :data-productColor="detail.productColor" :data-productId="detail.productId">点击购买(自动)</button>
            <button type="default" @tap="clickEvent">点击购买(手动)</button>
        </div>
    </div>
</template>

<script>
import { onAplusClk, record } from "../../utils/aplus_api";
export default {
    data() {
        return {
            detail: {
                product: '水杯',
				productColor: '黄色',
				productId: '003'
            }
        }
    },
    methods: {
        clickEvent: function() {			
            record("ClickToBuy", "CLK", {
                product: "床头灯2",
                productColor: "黄色2",
                productId: "id222",
            });		
        },
        onAplusClk: function(e) {
            onAplusClk(e)
        }
    }
}
</script>

<style lang="less">
.event-click {
    padding: 30px 5%;
}
.click-detail {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    margin: 30px 0 50px;
    img {
        width: 50%;
        height: 180px;
    }
    view {
        font-size: 18px;
        line-height: 30px;
    }
}
.click-purchase {
    display: flex;
    justify-content: space-between;
    button {
        width: 48%;
        margin: 0;
        font-size: 16px;
    }
}
</style>

// aplus_octopus/src/pages/click/click.tsx
import React, { Component } from 'react';
import { View, Image, Button } from "react-native";
import { onAplusClk, record } from '../../utils/aplus_api';
// import "./index.less";

export default class Click extends Component {
  constructor(props: any) {
    super(props);
    this.state = {};
  }

  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  // 页面分享事件日志上报时，需注册该方法
  // onShareAppMessage() {}

  render() {
    return (
      <View className="component" onClick={onAplusClk}>
        <View 
          className="container"
          style={{
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row'
          }}
        >
          <View style={{
            width: '60%'
          }}>
            <Image style={{ width: '100%' }} src="https://gd1.alicdn.com/imgextra/i4/2207297515629/O1CN01W5rDzt1rS89qNHD1f_!!2207297515629.jpg_400x400.jpg"></Image>
          </View>
          <View style={{
            width: '40%'
          }}>
            <View>商品名称: 床头灯</View>
            <View>颜色: 黄色</View>
            <View>商品ID: 003</View>
          </View>
        </View>
        
        <View style={{display: 'flex'}}>
          <View className="wrapper auto-click" data-keyword="auto-click"><Button title={"点击购买(自动)"}></Button></View>
          <View className="wrapper"><Button title={"点击购买(手动)"} onPress={() => {
            record('/ClickToBuy', 'CLK', {
              productName: '床头灯',
              price: '100'
            })
          }}></Button></View>
        </View>
      </View>
    );
  }
}
