// aplus_taro/src/pages/custom/custom.tsx
import React, { Component } from "react";
import Taro from "@tarojs/taro";
import { View, Image, Button } from "@tarojs/components";
import { record } from "../../utils/aplus_api";
// import "./index.less";

export default class Custom extends Component {
  constructor(props: any) {
    super(props);
    this.state = {};
  }

  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  // 页面分享事件日志上报时，需注册该方法
  onShareAppMessage() {}

  render() {
    return (
      <View className="component">
        <View
          className="container"
          style={{
            display: "flex",
            alignItems: "flex-end",
          }}
        >
          <View
            style={{
              width: "60%",
            }}
          >
            <Image
              style={{ width: "100%" }}
              src="https://gd1.alicdn.com/imgextra/i4/2207297515629/O1CN01W5rDzt1rS89qNHD1f_!!2207297515629.jpg_400x400.jpg"
            ></Image>
          </View>
          <View
            style={{
              width: "40%",
            }}
          >
            <View>商品名称: 床头灯</View>
            <View>颜色: 黄色</View>
            <View>商品ID: 003</View>
          </View>
        </View>

        <View style={{ display: "flex", justifyContent: "space-around" }}>
          <View className="wrapper">
            <Button
              onClick={() => {
                record("test_other_ekv", "OTHER", {
                  a: 1, b:2, c: 3
                });
              }}
            >
              点击购买
            </Button>
          </View>
        </View>
      </View>
    );
  }
}

// aplus_mpvue/src/pages/custom/index.vue
<template>
    <div class="event-click">
        <div class="click-detail">
            <img src="https://gd1.alicdn.com/imgextra/i4/2207297515629/O1CN01W5rDzt1rS89qNHD1f_!!2207297515629.jpg_400x400.jpg"/>
            <view><p v-for="(item, index) in detail" :key="index">{{item.name}}: {{item.value}}</p></view>
        </div>
        <button class="click-purchase" type="primary" @tap="navigateToClick">点击购买</button>
    </div>
</template>

<script>

export default {
  data () {
    return {
        detail: [
            {name: '商品名称', value: '床头灯'},
            {name: '颜色', value: '黄色'},
            {name: '商品ID', value: '003'}
        ]
    }
  },
  components: {
  },
  methods: {
  },

  created () {
    // let app = getApp()
  }
}
</script>

<style scoped>
.event-click {
    padding: 30px 5%;
}
.click-detail {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    margin: 30px 0 50px;
}
.click-detail img {
    width: 50%;
    height: 180px;
}
.click-detail view {
    font-size: 18px;
    line-height: 30px;
}
.click-purchase {
    width: 80%;
    display: flex;
    justify-content: center;
}
</style>
