// aplus_taro3x_native/src/pages/vt/vt.tsx
import React, { Component } from "react";
import Taro from "_@tarojs_taro@3.3.17@@tarojs/taro";
import {
  View,
  Swiper,
  SwiperItem,
  Image,
} from "_@tarojs_components@3.3.17@@tarojs/components";
import './vt.less'

class Vt extends Component {
  constructor(props: any) {
    super(props);
    this.state = {
      swiperImg: [
        {
          url: "https://img.alicdn.com/imgextra/i4/O1CN0198ZqQc1ipBYrWKD7b_!!6000000004461-0-tps-1316-736.jpg",
        },
        {
          url: "https://img.alicdn.com/imgextra/i1/O1CN01EdIpVV1jxiYfVOw8v_!!6000000004615-0-tps-1316-736.jpg",
        },
        {
          url: "https://img.alicdn.com/imgextra/i4/O1CN01RjAj8X1aJZIQk6G27_!!6000000003309-0-tps-1316-736.jpg",
        },
      ],
      indicatorDots: true,
      autoplay: true,
      interval: 2000,
      duration: 500,
      lists: [
        [
          {
            url: "https://gd1.alicdn.com/imgextra/i1/2028723128/O1CN01AHNoOr1YyfbGi6ogZ_!!2028723128.jpg",
            name: "大理石融蜡灯1",
            price: "￥379.0",
            scale: "73人购买",
            id: 1001,
          },
          {
            url: "https://gd3.alicdn.com/imgextra/i3/2209303074383/O1CN01E5T9QU1iFSeRLWz4s_!!2209303074383.jpg_400x400.jpg",
            name: "欧式大理石台灯",
            price: "189.0",
            scale: "898人购买",
            id: 1002,
          },
        ],
        [
          {
            url: "https://img.alicdn.com/imgextra/i3/2212630767092/O1CN01GlqcuM22GBbchND9Q_!!0-item_pic.jpg_430x430q90.jpg",
            name: "台灯学习专用护眼灯",
            price: "35.0",
            scale: "173人购买",
            id: 1003,
          },
          {
            url: "https://img.alicdn.com/imgextra/https://img.alicdn.com/imgextra/i1/138006397/O1CN01QWCvC01x7sJhTFYYS_!!138006397.jpg_430x430q90.jpg",
            name: "欧普AAA级护眼灯",
            price: "239.0",
            scale: "698人购买",
            id: 1004,
          },
        ],
        [
          {
            url: "https://img.alicdn.com/imgextra/i3/2103880744/O1CN012UZs071HMnMegbB33_!!2103880744.jpg_430x430q90.jpg",
            name: "壁灯卧室客厅背景墙灯",
            price: "69.0",
            scale: "222人购买",
            id: 1005,
          },
          {
            url: "https://gd1.alicdn.com/imgextra/i1/377720279/TB2Sev8e2NNTKJjSspfXXbXIFXa_!!377720279.jpg_400x400.jpg",
            name: "美式壁灯",
            price: "88.0",
            scale: "533人购买",
            id: 1006,
          },
        ],
        [
          {
            url: "https://img.alicdn.com/imgextra/i1/2211428522500/O1CN01GC0qjf1UL2qvYwB9P_!!2211428522500.jpg_430x430q90.jpg",
            name: "奥克斯风扇灯吊扇灯",
            price: "249.0",
            scale: "912人购买",
            id: 1007,
          },
          {
            url: "https://img.alicdn.com/imgextra/i2/2206769739534/O1CN01pKyg2S2KIcmMW9JWn_!!2206769739534.jpg_400x400.jpg",
            name: "隐形风扇灯吊扇灯",
            price: "158.0",
            scale: "752人购买",
            id: 1008,
          },
        ],
        [
          {
            url: "https://gd3.alicdn.com/imgextra/i2/2211780572115/O1CN01x4Tjsr1RUiMftry3t_!!2211780572115.jpg_400x400.jpg",
            name: "欧普照明led吸顶灯",
            price: "69.0",
            scale: "456人购买",
            id: 1009,
          },
          {
            url: "https://img.alicdn.com/imgextra/https://img.alicdn.com/imgextra/i3/2183118489/O1CN01v5bDLw2Ca0vVOMMLA_!!2183118489.jpg_430x430q90.jpg",
            name: "北欧吊灯客厅灯",
            price: "999.0",
            scale: "79人购买",
            id: 1010,
          },
        ],
      ],
    };
  }

  state: any;

  render() {
    const { swiperImg, indicatorDots, autoplay, interval, duration, lists } =
      this.state;
    return (
      <View className="event-exposure">
        <View className="exposure-auto">
          <View className="auto-title">场景1：轮播</View>
          <Swiper
            className="swiper"
            indicator-dots={indicatorDots}
            autoplay={autoplay}
            circular
            interval={interval}
            duration={duration}
          >
            {swiperImg.map((bg: any, idx: any) => {
              return (
                <SwiperItem
                  className="banner_item_vt"
                  style={{
                    width: "100%",
                    height: "100%",
                  }}
                >
                  <Image
                    data-keyword={`banner-item-${idx}`}
                    className="vt-banner-item "
                    key={idx}
                    data-index={idx}
                    src={bg.url}
                    style={{
                      width: "100%",
                      height: "100%",
                    }}
                  />
                </SwiperItem>
              );
            })}
          </Swiper>
        </View>
        <View className="exposure-manual">
          <View className="manual-title">场景2：瀑布流</View>
          {lists.map((list: any, index: number) => {
            return (
              <View key={index} className="exposure-grid vt-list-item">
                {list.map((item: any, idx: number) => {
                  return (
                    <View
                      className="exposure-grid-item-vt"
                      key={`${index}-${idx}`}
                      data-track-params={JSON.stringify(item)}
                    >
                      <View className="grid-item-box">
                        <Image src={item.url} />
                        <View>{item.name}</View>
                        <View className="grid-item-detail">
                          <View>
                            {item.price}+{index}
                          </View>
                          <View>
                            {item.scale}+{index}
                          </View>
                        </View>
                      </View>
                    </View>
                  );
                })}
              </View>
            );
          })}
        </View>
      </View>
    );
  }
}

export default Vt;

// aplus_mpvue/src/pages/vt/index.vue
<template>
    <div class="event-exposure">
        <div class="exposure-auto">
            <view>自动曝光</view>
            <swiper class="swiper" circular :indicator-dots="indicatorDots" :autoplay="autoplay" :interval="interval" :duration="duration">
                <swiper-item v-for="(item, index) in swiperImg" :key="index">
                    <img :src="item.url" alt="">
				</swiper-item>
			</swiper>
        </div>
        <div class="exposure-manual">
            <view>手动曝光</view>
            <section v-for="value in 2" :key="value" class="exposure-grid">
                <div v-for="(_item, _index) in list" :key="_index" class="exposure-grid-item">
                    <div class="grid-item-box">
                        <img :src="_item.url" alt="">
						<p>{{ _item.name }}</p>
                        <p class="grid-item-detail">
                            <span>{{ _item.price }}</span>
                            <span>{{ _item.scale }}</span>
                        </p>
					</div>
                </div>
            </section>
        </div>
    </div>
</template>

<script>

export default {
  data () {
    return {
        swiperImg: [
            {url: "https://img.alicdn.com/imgextra/i4/O1CN0198ZqQc1ipBYrWKD7b_!!6000000004461-0-tps-1316-736.jpg"},
            {url: "https://img.alicdn.com/imgextra/i1/O1CN01EdIpVV1jxiYfVOw8v_!!6000000004615-0-tps-1316-736.jpg"},
            {url: "https://img.alicdn.com/imgextra/i4/O1CN01RjAj8X1aJZIQk6G27_!!6000000003309-0-tps-1316-736.jpg"},
        ],
        background: ['color1', 'color2', 'color3'],
        indicatorDots: true,
        autoplay: true,
        interval: 2000,
        duration: 500,
        list: [
            {
                url: 'https://gd1.alicdn.com/imgextra/i4/2208928232857/O1CN019LfEfG1WyYGv4pMQ5_!!2208928232857.jpg_400x400.jpg',
                name: '大理石香薰灯',
                price: '￥129.0',
                scale: '88人购买'
            },
            {
                url: 'https://gd1.alicdn.com/imgextra/i1/2028723128/O1CN01AHNoOr1YyfbGi6ogZ_!!2028723128.jpg',
                name: '大理石融腊灯',
                price: '￥379.0',
                scale: '73人购买'
            }
        ]
    }
  },
  components: {
  },
  methods: {
  },

  created () {
    // let app = getApp()
  }
}
</script>

<style scoped>
.event-exposure {
    padding-bottom: 30px;
}
.exposure-auto view{
    font-size: 20px;
    padding: 15px 2% 10px;
}
.swiper {
    width: 100%;
    height: 211px;
}
.swiper img {
    width: 100%;
    height: 100%;
}
.exposure-manual view{
    font-size: 20px;
    padding: 15px 2% 0;
}
.exposure-grid {
    width: 100%;
    display: flex;
    justify-content: space-around;
    margin: 15px 0;
}
.exposure-grid-item {
    width: 45%;
    -webkit-box-shadow: #ccc 0px 0px 10px; 
    -moz-box-shadow: #ccc 0px 0px 10px;
}
.grid-item-box {
    display: flex;
    flex-direction: column;
    padding: 5%;
    font-size: 14px;
}
.grid-item-box img {
    width: 100%;
    height: 180px;
    margin-bottom: 8px;
}
.grid-item-detail span:first-child{
    color: red;
    font-size: 16px;
}
.grid-item-detail span:last-child {
    color: #aaa;
    margin-left: 5px;
    font-size: 16px;
}
</style>
